[package]
name = "tin"
version = "0.1.0"
authors = ["Andrew Lilley Brinker <andrewabrinker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
nom = "5.1.2"
thiserror = "1.0.20"
